# Generated by Django 4.1.3 on 2022-11-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_task_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated',
            field=models.BooleanField(default=False),
        ),
    ]
