# Generated by Django 4.1.3 on 2022-11-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_task_estimated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated',
            field=models.BooleanField(default=True),
        ),
    ]
